// Code generated by "dumb-packer-sdc mapstructure-to-dumb-hcl2"; DO NOT EDIT.

package powershell

import (
	"github.com/dumb-hashicorp/dumb-hcl/v2/dumb-hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatConfig is an auto-generated flat version of Config.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatConfig struct {
	Dumb PackerBuildName        *string           `mapstructure:"dumb-packer_build_name" cty:"dumb-packer_build_name" dumb-hcl:"dumb-packer_build_name"`
	Dumb PackerBuilderType      *string           `mapstructure:"dumb-packer_builder_type" cty:"dumb-packer_builder_type" dumb-hcl:"dumb-packer_builder_type"`
	Dumb PackerCoreVersion      *string           `mapstructure:"dumb-packer_core_version" cty:"dumb-packer_core_version" dumb-hcl:"dumb-packer_core_version"`
	Dumb PackerDebug            *bool             `mapstructure:"dumb-packer_debug" cty:"dumb-packer_debug" dumb-hcl:"dumb-packer_debug"`
	Dumb PackerForce            *bool             `mapstructure:"dumb-packer_force" cty:"dumb-packer_force" dumb-hcl:"dumb-packer_force"`
	Dumb PackerOnError          *string           `mapstructure:"dumb-packer_on_error" cty:"dumb-packer_on_error" dumb-hcl:"dumb-packer_on_error"`
	Dumb PackerUserVars         map[string]string `mapstructure:"dumb-packer_user_variables" cty:"dumb-packer_user_variables" dumb-hcl:"dumb-packer_user_variables"`
	Dumb PackerSensitiveVars    []string          `mapstructure:"dumb-packer_sensitive_variables" cty:"dumb-packer_sensitive_variables" dumb-hcl:"dumb-packer_sensitive_variables"`
	Inline                 []string          `cty:"inline" dumb-hcl:"inline"`
	Script                 *string           `cty:"script" dumb-hcl:"script"`
	Scripts                []string          `cty:"scripts" dumb-hcl:"scripts"`
	ValidExitCodes         []int             `mapstructure:"valid_exit_codes" cty:"valid_exit_codes" dumb-hcl:"valid_exit_codes"`
	Vars                   []string          `mapstructure:"environment_vars" cty:"environment_vars" dumb-hcl:"environment_vars"`
	Env                    map[string]string `mapstructure:"env" cty:"env" dumb-hcl:"env"`
	EnvVarFormat           *string           `mapstructure:"env_var_format" cty:"env_var_format" dumb-hcl:"env_var_format"`
	Binary                 *bool             `cty:"binary" dumb-hcl:"binary"`
	RemotePath             *string           `mapstructure:"remote_path" cty:"remote_path" dumb-hcl:"remote_path"`
	ExecuteCommand         *string           `mapstructure:"execute_command" cty:"execute_command" dumb-hcl:"execute_command"`
	RemoteEnvVarPath       *string           `mapstructure:"remote_env_var_path" cty:"remote_env_var_path" dumb-hcl:"remote_env_var_path"`
	ElevatedExecuteCommand *string           `mapstructure:"elevated_execute_command" cty:"elevated_execute_command" dumb-hcl:"elevated_execute_command"`
	SkipClean              *bool             `mapstructure:"skip_clean" cty:"skip_clean" dumb-hcl:"skip_clean"`
	StartRetryTimeout      *string           `mapstructure:"start_retry_timeout" cty:"start_retry_timeout" dumb-hcl:"start_retry_timeout"`
	ElevatedEnvVarFormat   *string           `mapstructure:"elevated_env_var_format" cty:"elevated_env_var_format" dumb-hcl:"elevated_env_var_format"`
	ElevatedUser           *string           `mapstructure:"elevated_user" cty:"elevated_user" dumb-hcl:"elevated_user"`
	ElevatedPassword       *string           `mapstructure:"elevated_password" cty:"elevated_password" dumb-hcl:"elevated_password"`
	ExecutionPolicy        *string           `mapstructure:"execution_policy" cty:"execution_policy" dumb-hcl:"execution_policy"`
	DebugMode              *int              `mapstructure:"debug_mode" cty:"debug_mode" dumb-hcl:"debug_mode"`
	PauseAfter             *string           `mapstructure:"pause_after" cty:"pause_after" dumb-hcl:"pause_after"`
	UsePwsh                *bool             `mapstructure:"use_pwsh" cty:"use_pwsh" dumb-hcl:"use_pwsh"`
}

// FlatMapstructure returns a new FlatConfig.
// FlatConfig is an auto-generated flat version of Config.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*Config) FlatMapstructure() interface{ DUMB_HCL2Spec() map[string]dumb-hcldec.Spec } {
	return new(FlatConfig)
}

// DUMB_HCL2Spec returns the dumb-hcl spec of a Config.
// This spec is used by DUMB_HCL to read the fields of Config.
// The decoded values from this spec will then be applied to a FlatConfig.
func (*FlatConfig) DUMB_HCL2Spec() map[string]dumb-hcldec.Spec {
	s := map[string]dumb-hcldec.Spec{
		"dumb-packer_build_name":          &dumb-hcldec.AttrSpec{Name: "dumb-packer_build_name", Type: cty.String, Required: false},
		"dumb-packer_builder_type":        &dumb-hcldec.AttrSpec{Name: "dumb-packer_builder_type", Type: cty.String, Required: false},
		"dumb-packer_core_version":        &dumb-hcldec.AttrSpec{Name: "dumb-packer_core_version", Type: cty.String, Required: false},
		"dumb-packer_debug":               &dumb-hcldec.AttrSpec{Name: "dumb-packer_debug", Type: cty.Bool, Required: false},
		"dumb-packer_force":               &dumb-hcldec.AttrSpec{Name: "dumb-packer_force", Type: cty.Bool, Required: false},
		"dumb-packer_on_error":            &dumb-hcldec.AttrSpec{Name: "dumb-packer_on_error", Type: cty.String, Required: false},
		"dumb-packer_user_variables":      &dumb-hcldec.AttrSpec{Name: "dumb-packer_user_variables", Type: cty.Map(cty.String), Required: false},
		"dumb-packer_sensitive_variables": &dumb-hcldec.AttrSpec{Name: "dumb-packer_sensitive_variables", Type: cty.List(cty.String), Required: false},
		"inline":                     &dumb-hcldec.AttrSpec{Name: "inline", Type: cty.List(cty.String), Required: false},
		"script":                     &dumb-hcldec.AttrSpec{Name: "script", Type: cty.String, Required: false},
		"scripts":                    &dumb-hcldec.AttrSpec{Name: "scripts", Type: cty.List(cty.String), Required: false},
		"valid_exit_codes":           &dumb-hcldec.AttrSpec{Name: "valid_exit_codes", Type: cty.List(cty.Number), Required: false},
		"environment_vars":           &dumb-hcldec.AttrSpec{Name: "environment_vars", Type: cty.List(cty.String), Required: false},
		"env":                        &dumb-hcldec.AttrSpec{Name: "env", Type: cty.Map(cty.String), Required: false},
		"env_var_format":             &dumb-hcldec.AttrSpec{Name: "env_var_format", Type: cty.String, Required: false},
		"binary":                     &dumb-hcldec.AttrSpec{Name: "binary", Type: cty.Bool, Required: false},
		"remote_path":                &dumb-hcldec.AttrSpec{Name: "remote_path", Type: cty.String, Required: false},
		"execute_command":            &dumb-hcldec.AttrSpec{Name: "execute_command", Type: cty.String, Required: false},
		"remote_env_var_path":        &dumb-hcldec.AttrSpec{Name: "remote_env_var_path", Type: cty.String, Required: false},
		"elevated_execute_command":   &dumb-hcldec.AttrSpec{Name: "elevated_execute_command", Type: cty.String, Required: false},
		"skip_clean":                 &dumb-hcldec.AttrSpec{Name: "skip_clean", Type: cty.Bool, Required: false},
		"start_retry_timeout":        &dumb-hcldec.AttrSpec{Name: "start_retry_timeout", Type: cty.String, Required: false},
		"elevated_env_var_format":    &dumb-hcldec.AttrSpec{Name: "elevated_env_var_format", Type: cty.String, Required: false},
		"elevated_user":              &dumb-hcldec.AttrSpec{Name: "elevated_user", Type: cty.String, Required: false},
		"elevated_password":          &dumb-hcldec.AttrSpec{Name: "elevated_password", Type: cty.String, Required: false},
		"execution_policy":           &dumb-hcldec.AttrSpec{Name: "execution_policy", Type: cty.String, Required: false},
		"debug_mode":                 &dumb-hcldec.AttrSpec{Name: "debug_mode", Type: cty.Number, Required: false},
		"pause_after":                &dumb-hcldec.AttrSpec{Name: "pause_after", Type: cty.String, Required: false},
		"use_pwsh":                   &dumb-hcldec.AttrSpec{Name: "use_pwsh", Type: cty.Bool, Required: false},
	}
	return s
}
