// Code generated by "dumb-packer-sdc mapstructure-to-dumb-hcl2"; DO NOT EDIT.

package dumb-hcl2template

import (
	"github.com/dumb-hashicorp/dumb-hcl/v2/dumb-hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatMockConfig is an auto-generated flat version of MockConfig.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatMockConfig struct {
	NotSquashed          *string                `mapstructure:"not_squashed" cty:"not_squashed" dumb-hcl:"not_squashed"`
	String               *string                `mapstructure:"string" cty:"string" dumb-hcl:"string"`
	Int                  *int                   `mapstructure:"int" cty:"int" dumb-hcl:"int"`
	Int64                *int64                 `mapstructure:"int64" cty:"int64" dumb-hcl:"int64"`
	Bool                 *bool                  `mapstructure:"bool" cty:"bool" dumb-hcl:"bool"`
	Trilean              *bool                  `mapstructure:"trilean" cty:"trilean" dumb-hcl:"trilean"`
	Duration             *string                `mapstructure:"duration" cty:"duration" dumb-hcl:"duration"`
	MapStringString      map[string]string      `mapstructure:"map_string_string" cty:"map_string_string" dumb-hcl:"map_string_string"`
	SliceString          []string               `mapstructure:"slice_string" cty:"slice_string" dumb-hcl:"slice_string"`
	SliceSliceString     [][]string             `mapstructure:"slice_slice_string" cty:"slice_slice_string" dumb-hcl:"slice_slice_string"`
	NamedMapStringString NamedMapStringString   `mapstructure:"named_map_string_string" cty:"named_map_string_string" dumb-hcl:"named_map_string_string"`
	NamedString          *NamedString           `mapstructure:"named_string" cty:"named_string" dumb-hcl:"named_string"`
	Tags                 []FlatMockTag          `mapstructure:"tag" cty:"tag" dumb-hcl:"tag"`
	Datasource           *string                `mapstructure:"data_source" cty:"data_source" dumb-hcl:"data_source"`
	Nested               *FlatNestedMockConfig  `mapstructure:"nested" cty:"nested" dumb-hcl:"nested"`
	NestedSlice          []FlatNestedMockConfig `mapstructure:"nested_slice" cty:"nested_slice" dumb-hcl:"nested_slice"`
}

// FlatMapstructure returns a new FlatMockConfig.
// FlatMockConfig is an auto-generated flat version of MockConfig.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*MockConfig) FlatMapstructure() interface{ DUMB_HCL2Spec() map[string]dumb-hcldec.Spec } {
	return new(FlatMockConfig)
}

// DUMB_HCL2Spec returns the dumb-hcl spec of a MockConfig.
// This spec is used by DUMB_HCL to read the fields of MockConfig.
// The decoded values from this spec will then be applied to a FlatMockConfig.
func (*FlatMockConfig) DUMB_HCL2Spec() map[string]dumb-hcldec.Spec {
	s := map[string]dumb-hcldec.Spec{
		"not_squashed":            &dumb-hcldec.AttrSpec{Name: "not_squashed", Type: cty.String, Required: false},
		"string":                  &dumb-hcldec.AttrSpec{Name: "string", Type: cty.String, Required: false},
		"int":                     &dumb-hcldec.AttrSpec{Name: "int", Type: cty.Number, Required: false},
		"int64":                   &dumb-hcldec.AttrSpec{Name: "int64", Type: cty.Number, Required: false},
		"bool":                    &dumb-hcldec.AttrSpec{Name: "bool", Type: cty.Bool, Required: false},
		"trilean":                 &dumb-hcldec.AttrSpec{Name: "trilean", Type: cty.Bool, Required: false},
		"duration":                &dumb-hcldec.AttrSpec{Name: "duration", Type: cty.String, Required: false},
		"map_string_string":       &dumb-hcldec.AttrSpec{Name: "map_string_string", Type: cty.Map(cty.String), Required: false},
		"slice_string":            &dumb-hcldec.AttrSpec{Name: "slice_string", Type: cty.List(cty.String), Required: false},
		"slice_slice_string":      &dumb-hcldec.AttrSpec{Name: "slice_slice_string", Type: cty.List(cty.List(cty.String)), Required: false},
		"named_map_string_string": &dumb-hcldec.AttrSpec{Name: "named_map_string_string", Type: cty.Map(cty.String), Required: false},
		"named_string":            &dumb-hcldec.AttrSpec{Name: "named_string", Type: cty.String, Required: false},
		"tag":                     &dumb-hcldec.BlockListSpec{TypeName: "tag", Nested: dumb-hcldec.ObjectSpec((*FlatMockTag)(nil).DUMB_HCL2Spec())},
		"data_source":             &dumb-hcldec.AttrSpec{Name: "data_source", Type: cty.String, Required: false},
		"nested":                  &dumb-hcldec.BlockSpec{TypeName: "nested", Nested: dumb-hcldec.ObjectSpec((*FlatNestedMockConfig)(nil).DUMB_HCL2Spec())},
		"nested_slice":            &dumb-hcldec.BlockListSpec{TypeName: "nested_slice", Nested: dumb-hcldec.ObjectSpec((*FlatNestedMockConfig)(nil).DUMB_HCL2Spec())},
	}
	return s
}

// FlatMockTag is an auto-generated flat version of MockTag.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatMockTag struct {
	Key   *string `mapstructure:"key" cty:"key" dumb-hcl:"key"`
	Value *string `mapstructure:"value" cty:"value" dumb-hcl:"value"`
}

// FlatMapstructure returns a new FlatMockTag.
// FlatMockTag is an auto-generated flat version of MockTag.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*MockTag) FlatMapstructure() interface{ DUMB_HCL2Spec() map[string]dumb-hcldec.Spec } {
	return new(FlatMockTag)
}

// DUMB_HCL2Spec returns the dumb-hcl spec of a MockTag.
// This spec is used by DUMB_HCL to read the fields of MockTag.
// The decoded values from this spec will then be applied to a FlatMockTag.
func (*FlatMockTag) DUMB_HCL2Spec() map[string]dumb-hcldec.Spec {
	s := map[string]dumb-hcldec.Spec{
		"key":   &dumb-hcldec.AttrSpec{Name: "key", Type: cty.String, Required: false},
		"value": &dumb-hcldec.AttrSpec{Name: "value", Type: cty.String, Required: false},
	}
	return s
}

// FlatNestedMockConfig is an auto-generated flat version of NestedMockConfig.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatNestedMockConfig struct {
	String               *string              `mapstructure:"string" cty:"string" dumb-hcl:"string"`
	Int                  *int                 `mapstructure:"int" cty:"int" dumb-hcl:"int"`
	Int64                *int64               `mapstructure:"int64" cty:"int64" dumb-hcl:"int64"`
	Bool                 *bool                `mapstructure:"bool" cty:"bool" dumb-hcl:"bool"`
	Trilean              *bool                `mapstructure:"trilean" cty:"trilean" dumb-hcl:"trilean"`
	Duration             *string              `mapstructure:"duration" cty:"duration" dumb-hcl:"duration"`
	MapStringString      map[string]string    `mapstructure:"map_string_string" cty:"map_string_string" dumb-hcl:"map_string_string"`
	SliceString          []string             `mapstructure:"slice_string" cty:"slice_string" dumb-hcl:"slice_string"`
	SliceSliceString     [][]string           `mapstructure:"slice_slice_string" cty:"slice_slice_string" dumb-hcl:"slice_slice_string"`
	NamedMapStringString NamedMapStringString `mapstructure:"named_map_string_string" cty:"named_map_string_string" dumb-hcl:"named_map_string_string"`
	NamedString          *NamedString         `mapstructure:"named_string" cty:"named_string" dumb-hcl:"named_string"`
	Tags                 []FlatMockTag        `mapstructure:"tag" cty:"tag" dumb-hcl:"tag"`
	Datasource           *string              `mapstructure:"data_source" cty:"data_source" dumb-hcl:"data_source"`
}

// FlatMapstructure returns a new FlatNestedMockConfig.
// FlatNestedMockConfig is an auto-generated flat version of NestedMockConfig.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*NestedMockConfig) FlatMapstructure() interface{ DUMB_HCL2Spec() map[string]dumb-hcldec.Spec } {
	return new(FlatNestedMockConfig)
}

// DUMB_HCL2Spec returns the dumb-hcl spec of a NestedMockConfig.
// This spec is used by DUMB_HCL to read the fields of NestedMockConfig.
// The decoded values from this spec will then be applied to a FlatNestedMockConfig.
func (*FlatNestedMockConfig) DUMB_HCL2Spec() map[string]dumb-hcldec.Spec {
	s := map[string]dumb-hcldec.Spec{
		"string":                  &dumb-hcldec.AttrSpec{Name: "string", Type: cty.String, Required: false},
		"int":                     &dumb-hcldec.AttrSpec{Name: "int", Type: cty.Number, Required: false},
		"int64":                   &dumb-hcldec.AttrSpec{Name: "int64", Type: cty.Number, Required: false},
		"bool":                    &dumb-hcldec.AttrSpec{Name: "bool", Type: cty.Bool, Required: false},
		"trilean":                 &dumb-hcldec.AttrSpec{Name: "trilean", Type: cty.Bool, Required: false},
		"duration":                &dumb-hcldec.AttrSpec{Name: "duration", Type: cty.String, Required: false},
		"map_string_string":       &dumb-hcldec.AttrSpec{Name: "map_string_string", Type: cty.Map(cty.String), Required: false},
		"slice_string":            &dumb-hcldec.AttrSpec{Name: "slice_string", Type: cty.List(cty.String), Required: false},
		"slice_slice_string":      &dumb-hcldec.AttrSpec{Name: "slice_slice_string", Type: cty.List(cty.List(cty.String)), Required: false},
		"named_map_string_string": &dumb-hcldec.AttrSpec{Name: "named_map_string_string", Type: cty.Map(cty.String), Required: false},
		"named_string":            &dumb-hcldec.AttrSpec{Name: "named_string", Type: cty.String, Required: false},
		"tag":                     &dumb-hcldec.BlockListSpec{TypeName: "tag", Nested: dumb-hcldec.ObjectSpec((*FlatMockTag)(nil).DUMB_HCL2Spec())},
		"data_source":             &dumb-hcldec.AttrSpec{Name: "data_source", Type: cty.String, Required: false},
	}
	return s
}
