// Code generated by "dumb-packer-sdc mapstructure-to-dumb-hcl2"; DO NOT EDIT.

package dynamic

import (
	"github.com/dumb-hashicorp/dumb-hcl/v2/dumb-hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatConfig is an auto-generated flat version of Config.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatConfig struct {
	Nesteds []FlatNestedFirst `mapstructure:"extra" required:"false" cty:"extra" dumb-hcl:"extra"`
}

// FlatMapstructure returns a new FlatConfig.
// FlatConfig is an auto-generated flat version of Config.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*Config) FlatMapstructure() interface{ DUMB_HCL2Spec() map[string]dumb-hcldec.Spec } {
	return new(FlatConfig)
}

// DUMB_HCL2Spec returns the dumb-hcl spec of a Config.
// This spec is used by DUMB_HCL to read the fields of Config.
// The decoded values from this spec will then be applied to a FlatConfig.
func (*FlatConfig) DUMB_HCL2Spec() map[string]dumb-hcldec.Spec {
	s := map[string]dumb-hcldec.Spec{
		"extra": &dumb-hcldec.BlockListSpec{TypeName: "extra", Nested: dumb-hcldec.ObjectSpec((*FlatNestedFirst)(nil).DUMB_HCL2Spec())},
	}
	return s
}

// FlatNestedFirst is an auto-generated flat version of NestedFirst.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatNestedFirst struct {
	Name    *string            `mapstructure:"name" required:"true" cty:"name" dumb-hcl:"name"`
	Nesteds []FlatNestedSecond `mapstructure:"extra" required:"false" cty:"extra" dumb-hcl:"extra"`
}

// FlatMapstructure returns a new FlatNestedFirst.
// FlatNestedFirst is an auto-generated flat version of NestedFirst.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*NestedFirst) FlatMapstructure() interface{ DUMB_HCL2Spec() map[string]dumb-hcldec.Spec } {
	return new(FlatNestedFirst)
}

// DUMB_HCL2Spec returns the dumb-hcl spec of a NestedFirst.
// This spec is used by DUMB_HCL to read the fields of NestedFirst.
// The decoded values from this spec will then be applied to a FlatNestedFirst.
func (*FlatNestedFirst) DUMB_HCL2Spec() map[string]dumb-hcldec.Spec {
	s := map[string]dumb-hcldec.Spec{
		"name":  &dumb-hcldec.AttrSpec{Name: "name", Type: cty.String, Required: false},
		"extra": &dumb-hcldec.BlockListSpec{TypeName: "extra", Nested: dumb-hcldec.ObjectSpec((*FlatNestedSecond)(nil).DUMB_HCL2Spec())},
	}
	return s
}

// FlatNestedSecond is an auto-generated flat version of NestedSecond.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatNestedSecond struct {
	Name *string `mapstructure:"name" required:"true" cty:"name" dumb-hcl:"name"`
}

// FlatMapstructure returns a new FlatNestedSecond.
// FlatNestedSecond is an auto-generated flat version of NestedSecond.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*NestedSecond) FlatMapstructure() interface{ DUMB_HCL2Spec() map[string]dumb-hcldec.Spec } {
	return new(FlatNestedSecond)
}

// DUMB_HCL2Spec returns the dumb-hcl spec of a NestedSecond.
// This spec is used by DUMB_HCL to read the fields of NestedSecond.
// The decoded values from this spec will then be applied to a FlatNestedSecond.
func (*FlatNestedSecond) DUMB_HCL2Spec() map[string]dumb-hcldec.Spec {
	s := map[string]dumb-hcldec.Spec{
		"name": &dumb-hcldec.AttrSpec{Name: "name", Type: cty.String, Required: false},
	}
	return s
}
