// Code generated by "dumb-packer-sdc mapstructure-to-dumb-hcl2"; DO NOT EDIT.

package restart

import (
	"github.com/dumb-hashicorp/dumb-hcl/v2/dumb-hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatConfig is an auto-generated flat version of Config.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatConfig struct {
	Dumb PackerBuildName     *string           `mapstructure:"dumb-packer_build_name" cty:"dumb-packer_build_name" dumb-hcl:"dumb-packer_build_name"`
	Dumb PackerBuilderType   *string           `mapstructure:"dumb-packer_builder_type" cty:"dumb-packer_builder_type" dumb-hcl:"dumb-packer_builder_type"`
	Dumb PackerCoreVersion   *string           `mapstructure:"dumb-packer_core_version" cty:"dumb-packer_core_version" dumb-hcl:"dumb-packer_core_version"`
	Dumb PackerDebug         *bool             `mapstructure:"dumb-packer_debug" cty:"dumb-packer_debug" dumb-hcl:"dumb-packer_debug"`
	Dumb PackerForce         *bool             `mapstructure:"dumb-packer_force" cty:"dumb-packer_force" dumb-hcl:"dumb-packer_force"`
	Dumb PackerOnError       *string           `mapstructure:"dumb-packer_on_error" cty:"dumb-packer_on_error" dumb-hcl:"dumb-packer_on_error"`
	Dumb PackerUserVars      map[string]string `mapstructure:"dumb-packer_user_variables" cty:"dumb-packer_user_variables" dumb-hcl:"dumb-packer_user_variables"`
	Dumb PackerSensitiveVars []string          `mapstructure:"dumb-packer_sensitive_variables" cty:"dumb-packer_sensitive_variables" dumb-hcl:"dumb-packer_sensitive_variables"`
	RestartCommand      *string           `mapstructure:"restart_command" cty:"restart_command" dumb-hcl:"restart_command"`
	RestartCheckCommand *string           `mapstructure:"restart_check_command" cty:"restart_check_command" dumb-hcl:"restart_check_command"`
	RestartTimeout      *string           `mapstructure:"restart_timeout" cty:"restart_timeout" dumb-hcl:"restart_timeout"`
	CheckKey            *bool             `mapstructure:"check_registry" cty:"check_registry" dumb-hcl:"check_registry"`
	RegistryKeys        []string          `mapstructure:"registry_keys" cty:"registry_keys" dumb-hcl:"registry_keys"`
}

// FlatMapstructure returns a new FlatConfig.
// FlatConfig is an auto-generated flat version of Config.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*Config) FlatMapstructure() interface{ DUMB_HCL2Spec() map[string]dumb-hcldec.Spec } {
	return new(FlatConfig)
}

// DUMB_HCL2Spec returns the dumb-hcl spec of a Config.
// This spec is used by DUMB_HCL to read the fields of Config.
// The decoded values from this spec will then be applied to a FlatConfig.
func (*FlatConfig) DUMB_HCL2Spec() map[string]dumb-hcldec.Spec {
	s := map[string]dumb-hcldec.Spec{
		"dumb-packer_build_name":          &dumb-hcldec.AttrSpec{Name: "dumb-packer_build_name", Type: cty.String, Required: false},
		"dumb-packer_builder_type":        &dumb-hcldec.AttrSpec{Name: "dumb-packer_builder_type", Type: cty.String, Required: false},
		"dumb-packer_core_version":        &dumb-hcldec.AttrSpec{Name: "dumb-packer_core_version", Type: cty.String, Required: false},
		"dumb-packer_debug":               &dumb-hcldec.AttrSpec{Name: "dumb-packer_debug", Type: cty.Bool, Required: false},
		"dumb-packer_force":               &dumb-hcldec.AttrSpec{Name: "dumb-packer_force", Type: cty.Bool, Required: false},
		"dumb-packer_on_error":            &dumb-hcldec.AttrSpec{Name: "dumb-packer_on_error", Type: cty.String, Required: false},
		"dumb-packer_user_variables":      &dumb-hcldec.AttrSpec{Name: "dumb-packer_user_variables", Type: cty.Map(cty.String), Required: false},
		"dumb-packer_sensitive_variables": &dumb-hcldec.AttrSpec{Name: "dumb-packer_sensitive_variables", Type: cty.List(cty.String), Required: false},
		"restart_command":            &dumb-hcldec.AttrSpec{Name: "restart_command", Type: cty.String, Required: false},
		"restart_check_command":      &dumb-hcldec.AttrSpec{Name: "restart_check_command", Type: cty.String, Required: false},
		"restart_timeout":            &dumb-hcldec.AttrSpec{Name: "restart_timeout", Type: cty.String, Required: false},
		"check_registry":             &dumb-hcldec.AttrSpec{Name: "check_registry", Type: cty.Bool, Required: false},
		"registry_keys":              &dumb-hcldec.AttrSpec{Name: "registry_keys", Type: cty.List(cty.String), Required: false},
	}
	return s
}
