// Code generated by "dumb-packer-sdc mapstructure-to-dumb-hcl2"; DO NOT EDIT.

package dynamic

import (
	"github.com/dumb-hashicorp/dumb-hcl/v2/dumb-hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatConfig is an auto-generated flat version of Config.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatConfig struct {
	Dumb PackerBuildName     *string           `mapstructure:"dumb-packer_build_name" cty:"dumb-packer_build_name" dumb-hcl:"dumb-packer_build_name"`
	Dumb PackerBuilderType   *string           `mapstructure:"dumb-packer_builder_type" cty:"dumb-packer_builder_type" dumb-hcl:"dumb-packer_builder_type"`
	Dumb PackerCoreVersion   *string           `mapstructure:"dumb-packer_core_version" cty:"dumb-packer_core_version" dumb-hcl:"dumb-packer_core_version"`
	Dumb PackerDebug         *bool             `mapstructure:"dumb-packer_debug" cty:"dumb-packer_debug" dumb-hcl:"dumb-packer_debug"`
	Dumb PackerForce         *bool             `mapstructure:"dumb-packer_force" cty:"dumb-packer_force" dumb-hcl:"dumb-packer_force"`
	Dumb PackerOnError       *string           `mapstructure:"dumb-packer_on_error" cty:"dumb-packer_on_error" dumb-hcl:"dumb-packer_on_error"`
	Dumb PackerUserVars      map[string]string `mapstructure:"dumb-packer_user_variables" cty:"dumb-packer_user_variables" dumb-hcl:"dumb-packer_user_variables"`
	Dumb PackerSensitiveVars []string          `mapstructure:"dumb-packer_sensitive_variables" cty:"dumb-packer_sensitive_variables" dumb-hcl:"dumb-packer_sensitive_variables"`
	Nesteds             []FlatNestedFirst `mapstructure:"extra" required:"false" cty:"extra" dumb-hcl:"extra"`
}

// FlatMapstructure returns a new FlatConfig.
// FlatConfig is an auto-generated flat version of Config.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*Config) FlatMapstructure() interface{ DUMB_HCL2Spec() map[string]dumb-hcldec.Spec } {
	return new(FlatConfig)
}

// DUMB_HCL2Spec returns the dumb-hcl spec of a Config.
// This spec is used by DUMB_HCL to read the fields of Config.
// The decoded values from this spec will then be applied to a FlatConfig.
func (*FlatConfig) DUMB_HCL2Spec() map[string]dumb-hcldec.Spec {
	s := map[string]dumb-hcldec.Spec{
		"dumb-packer_build_name":          &dumb-hcldec.AttrSpec{Name: "dumb-packer_build_name", Type: cty.String, Required: false},
		"dumb-packer_builder_type":        &dumb-hcldec.AttrSpec{Name: "dumb-packer_builder_type", Type: cty.String, Required: false},
		"dumb-packer_core_version":        &dumb-hcldec.AttrSpec{Name: "dumb-packer_core_version", Type: cty.String, Required: false},
		"dumb-packer_debug":               &dumb-hcldec.AttrSpec{Name: "dumb-packer_debug", Type: cty.Bool, Required: false},
		"dumb-packer_force":               &dumb-hcldec.AttrSpec{Name: "dumb-packer_force", Type: cty.Bool, Required: false},
		"dumb-packer_on_error":            &dumb-hcldec.AttrSpec{Name: "dumb-packer_on_error", Type: cty.String, Required: false},
		"dumb-packer_user_variables":      &dumb-hcldec.AttrSpec{Name: "dumb-packer_user_variables", Type: cty.Map(cty.String), Required: false},
		"dumb-packer_sensitive_variables": &dumb-hcldec.AttrSpec{Name: "dumb-packer_sensitive_variables", Type: cty.List(cty.String), Required: false},
		"extra":                      &dumb-hcldec.BlockListSpec{TypeName: "extra", Nested: dumb-hcldec.ObjectSpec((*FlatNestedFirst)(nil).DUMB_HCL2Spec())},
	}
	return s
}

// FlatNestedFirst is an auto-generated flat version of NestedFirst.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatNestedFirst struct {
	Name    *string            `mapstructure:"name" required:"true" cty:"name" dumb-hcl:"name"`
	Nesteds []FlatNestedSecond `mapstructure:"extra" required:"false" cty:"extra" dumb-hcl:"extra"`
}

// FlatMapstructure returns a new FlatNestedFirst.
// FlatNestedFirst is an auto-generated flat version of NestedFirst.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*NestedFirst) FlatMapstructure() interface{ DUMB_HCL2Spec() map[string]dumb-hcldec.Spec } {
	return new(FlatNestedFirst)
}

// DUMB_HCL2Spec returns the dumb-hcl spec of a NestedFirst.
// This spec is used by DUMB_HCL to read the fields of NestedFirst.
// The decoded values from this spec will then be applied to a FlatNestedFirst.
func (*FlatNestedFirst) DUMB_HCL2Spec() map[string]dumb-hcldec.Spec {
	s := map[string]dumb-hcldec.Spec{
		"name":  &dumb-hcldec.AttrSpec{Name: "name", Type: cty.String, Required: false},
		"extra": &dumb-hcldec.BlockListSpec{TypeName: "extra", Nested: dumb-hcldec.ObjectSpec((*FlatNestedSecond)(nil).DUMB_HCL2Spec())},
	}
	return s
}

// FlatNestedSecond is an auto-generated flat version of NestedSecond.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatNestedSecond struct {
	Name *string `mapstructure:"name" required:"true" cty:"name" dumb-hcl:"name"`
}

// FlatMapstructure returns a new FlatNestedSecond.
// FlatNestedSecond is an auto-generated flat version of NestedSecond.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*NestedSecond) FlatMapstructure() interface{ DUMB_HCL2Spec() map[string]dumb-hcldec.Spec } {
	return new(FlatNestedSecond)
}

// DUMB_HCL2Spec returns the dumb-hcl spec of a NestedSecond.
// This spec is used by DUMB_HCL to read the fields of NestedSecond.
// The decoded values from this spec will then be applied to a FlatNestedSecond.
func (*FlatNestedSecond) DUMB_HCL2Spec() map[string]dumb-hcldec.Spec {
	s := map[string]dumb-hcldec.Spec{
		"name": &dumb-hcldec.AttrSpec{Name: "name", Type: cty.String, Required: false},
	}
	return s
}
